### ISSUE TITLE
Not working on Linux - LibreOffice-7.3.2.2

### ISSUE THREAD

**Issue by arossato** [jeremymarch/hopliteKB-LibreOffice#2]
Hello,

very nice tool. I'd like to use it on linux. I followed the instructions but using ctrl-1-9 doesn't produce the expected result.

Even with the combining only mode diacritics are not being added. Moreover the default key bindings, which I'm currently using on Writer, for CTRL-1-5 are just modifying the heading level of the text.

I know it is not a font problem: I'm using New Athena Unicode and wrote an emacs input method that works just fine with PUA.

I didn't study the code, so I think that maybe I'm just missing something but, unfortunately, the documentation is not helpful.

Thanks for your kind attention.

**Comment by arossato** [comment]
After digging into the code I found what I was doing wrong...

I think that the readme file is a bit misleading, though: "After typing a vowel, while holding Control (Command on Mac), press a key 1-9 to toggle on/off diacritics." I do not know if this is outdated, but I found that after toggling the HK with the toolbar  icon you do not need to press CTRL.

Sorry for the noise.

**Comment by jeremymarch** [comment]
Sorry, about that.  The readme is still documenting the older version.  I will update it.
